[package]
name = "kazaam"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
hound = "3.5.1"
json = "0.12.4"
json-writer = "0.4.0"
plotters = "0.3.7"
sonogram = "0.7.1"
spectrum-analyzer = "1.6.0"
symphonia = "0.5.4"
