[package]
name = "kazaam"
version = "0.1.0"
edition = "2024"

[dependencies]
apodize = "1.0.0"
cpal = "0.15.3"
hound = "3.5.1"
json = "0.12.4"
json-writer = "0.4.0"
plotters = "0.3.7"
realfft = "3.4.0"
rustfft = "6.2.0"
sonogram = "0.7.1"
spectrum-analyzer = "1.6.0"
